line-length = 120

exclude = [
    "tests/fixtures",
    "tests/test_data",
    "fixtures",
    "test_data",
    "dummy_*.py",
    ".venv",
]

[lint]
ignore = [
    "BLE001",
    "S110",
    "S112",
    "SIM102",
    "B008",
]

[lint.per-file-ignores]
"tests/*" = ["SIM117", "RUF059", "DTZ005", "DTZ011", "F841"]
