"""Semantic AI Slop Classifier for WARDEN.

Identifies LLM-generated code comments, docstrings, and commentary patterns:
- Didactic/tutorial commentary ("# Import necessary libraries", "# Step 1: Initialize...")
- Redundant echo comments that duplicate function/variable names without adding insight
- Conversational openings/closings ("Here is the updated code", "I hope this helps")
- Boilerplate disclaimers ("In production, replace this with a secure API key")
- Markdown and prompt leakage markers within code

Uses TF-IDF + linear feature weighting with graceful pure-Python fallback.
"""

from __future__ import annotations

import logging
import math
import re
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)

# Heuristic patterns associated with AI-generated commentary
DIDACTIC_PATTERNS: list[tuple[re.Pattern[str], str, float]] = [
    (re.compile(r"^\s*#\s*(import(ing)?\s+(all\s+)?(necessary|required|the)\s+(modules|packages|libraries|dependencies))", re.I), "didactic_import", 3.5),
    (re.compile(r"^\s*#\s*(helper\s+function\s+to|function\s+to\s+(handle|calculate|process|format|execute))", re.I), "obvious_function_label", 2.5),
    (re.compile(r"^\s*#\s*(step\s+\d+[:\.]?\s*\w+)", re.I), "procedural_step", 2.5),
    (re.compile(r"^\s*#\s*(create\s+(an?\s+)?instance\s+of|initialize\s+(the\s+)?(class|variables?|object))", re.I), "obvious_instantiation", 2.5),
    (re.compile(r"^\s*#\s*(loop\s+(through|over)\s+(the\s+)?(items|elements|list|data))", re.I), "obvious_loop", 2.5),
    (re.compile(r"^\s*#\s*(call\s+(the\s+)?function|return\s+(the\s+)?(result|response|value))", re.I), "obvious_call_or_return", 2.0),
    (re.compile(r"^\s*#\s*(constructor\s+method|getter\s+for|setter\s+for)", re.I), "obvious_oop_comment", 2.0),
]

DISCLAIMER_PATTERNS: list[tuple[re.Pattern[str], str, float]] = [
    (re.compile(r"#\s*(in\s+production,?\s+(you\s+should|replace|use|implement|make\s+sure))", re.I), "production_disclaimer", 4.0),
    (re.compile(r"#\s*(replace\s+(this\s+)?with\s+your\s+(actual\s+)?(api_?key|token|secret|url|credentials))", re.I), "placeholder_disclaimer", 4.5),
    (re.compile(r"#\s*(for\s+(demonstration|testing|example)\s+purposes?\s+only)", re.I), "demo_disclaimer", 3.5),
    (re.compile(r"#\s*(note:\s*(this\s+is\s+a\s+(mock|simple|basic|minimal)|make\s+sure\s+to))", re.I), "mock_disclaimer", 3.0),
    (re.compile(r"#\s*(ensure\s+(proper\s+)?error\s+handling\s+is\s+(added|implemented))", re.I), "error_disclaimer", 3.0),
]

CONVERSATIONAL_PATTERNS: list[tuple[re.Pattern[str], str, float]] = [
    (re.compile(r"#\s*(here\s+is\s+(the\s+)?(updated|complete|refactored|full)\s+(code|implementation|solution))", re.I), "chat_here_is_code", 5.0),
    (re.compile(r"#\s*(feel\s+free\s+to\s+(modify|adjust|customize|extend|tweak))", re.I), "chat_feel_free", 4.5),
    (re.compile(r"#\s*(i\s+hope\s+this\s+(helps|is\s+helpful))", re.I), "chat_i_hope_this_helps", 5.0),
    (re.compile(r"#\s*(let\s+me\s+know\s+if\s+you\s+(have|need))", re.I), "chat_let_me_know", 5.0),
    (re.compile(r"#\s*(as\s+requested,?\s+here)", re.I), "chat_as_requested", 5.0),
    (re.compile(r"```(?:python|bash|json|javascript|ts)?", re.I), "markdown_code_fence", 5.0),
]

# High-frequency AI slop n-grams for TF-IDF / dictionary weighting
SLOP_KEYWORD_WEIGHTS: dict[str, float] = {
    "import necessary": 2.5,
    "necessary libraries": 2.5,
    "required packages": 2.0,
    "helper function": 2.0,
    "step 1": 2.0,
    "step 2": 2.0,
    "in production": 3.0,
    "replace with your": 3.5,
    "for demonstration purposes": 3.0,
    "mock implementation": 2.5,
    "here is the": 3.0,
    "feel free to": 3.5,
    "hope this helps": 4.0,
    "let me know": 3.5,
    "simple implementation": 2.0,
    "basic example": 2.0,
    "initialize variables": 2.0,
}


@dataclass
class SlopClassificationResult:
    """Result of classifying a comment or code segment for AI slop."""

    label: str  # "human" | "ai_slop" | "mixed"
    confidence: float  # 0.0 to 1.0
    slop_score: float  # 0.0 to 100.0
    features: dict[str, float] = field(default_factory=dict)
    matched_markers: list[str] = field(default_factory=list)
    explanation: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "label": self.label,
            "confidence": round(self.confidence, 3),
            "slop_score": round(self.slop_score, 1),
            "features": {k: round(v, 3) for k, v in self.features.items()},
            "matched_markers": self.matched_markers,
            "explanation": self.explanation,
        }


class AISlopClassifier:
    """Classifier evaluating the semantic authenticity of code commentary and docstrings.

    Distinguishes genuine human developer intent from mechanical, didactic, or
    conversational AI slop generated by LLMs (ChatGPT, Copilot, Claude).
    """

    def __init__(self, use_sklearn: bool = True) -> None:
        self.use_sklearn = use_sklearn
        self._sklearn_available = False
        self._vectorizer = None

        if self.use_sklearn:
            try:
                from sklearn.feature_extraction.text import TfidfVectorizer

                self._vectorizer = TfidfVectorizer(
                    ngram_range=(1, 3),
                    lowercase=True,
                    vocabulary=list(SLOP_KEYWORD_WEIGHTS.keys()),
                )
                self._sklearn_available = True
            except ImportError:
                logger.debug("scikit-learn not available, using pure-Python TF-IDF fallback")
                self._sklearn_available = False

    def _extract_heuristic_features(self, text: str) -> tuple[float, list[str], dict[str, float]]:
        """Extracts didactic, disclaimer, and conversational features from text."""
        total_score = 0.0
        markers: list[str] = []
        features: dict[str, float] = {
            "didactic": 0.0,
            "disclaimer": 0.0,
            "conversational": 0.0,
            "keyword_density": 0.0,
            "echo_redundancy": 0.0,
        }

        # 1. Didactic checks
        for pat, name, weight in DIDACTIC_PATTERNS:
            if pat.search(text):
                total_score += weight * 10.0
                markers.append(name)
                features["didactic"] += weight

        # 2. Disclaimer checks
        for pat, name, weight in DISCLAIMER_PATTERNS:
            if pat.search(text):
                total_score += weight * 12.0
                markers.append(name)
                features["disclaimer"] += weight

        # 3. Conversational checks
        for pat, name, weight in CONVERSATIONAL_PATTERNS:
            if pat.search(text):
                total_score += weight * 15.0
                markers.append(name)
                features["conversational"] += weight

        # 4. N-gram / Keyword weights
        lower_text = text.lower()
        keyword_hits = 0.0
        for kw, weight in SLOP_KEYWORD_WEIGHTS.items():
            if kw in lower_text:
                keyword_hits += weight
                if kw not in markers:
                    markers.append(f"kw:{kw}")
        features["keyword_density"] = keyword_hits
        total_score += keyword_hits * 5.0

        return total_score, markers, features

    def _calculate_echo_redundancy(self, comment: str, surrounding_code: str | None = None) -> float:
        """Measures whether a comment simply echoes identifiers from the next line.

        Example:
        `# get user by id` followed by `def get_user_by_id(user_id):`
        returns high echo redundancy.
        """
        if not surrounding_code:
            return 0.0

        # Extract words from comment, splitting camelCase and snake_case
        expanded_comment = re.sub(r"([a-z])([A-Z])", r"\1 \2", comment)
        clean_comment = re.sub(r"[^\w\s]|_", " ", expanded_comment.lower()).strip()
        comment_words = set(w for w in clean_comment.split() if len(w) >= 2)
        if not comment_words:
            return 0.0

        # Extract words from surrounding code line, splitting camelCase and snake_case
        expanded_code = re.sub(r"([a-z])([A-Z])", r"\1 \2", surrounding_code)
        clean_code = re.sub(r"[^\w\s]|_", " ", expanded_code.lower()).strip()
        code_words = set(w for w in clean_code.split() if len(w) >= 2)
        if not code_words:
            return 0.0

        intersection = comment_words.intersection(code_words)
        overlap_ratio = len(intersection) / len(comment_words)
        return overlap_ratio

    def classify_text(
        self,
        text: str,
        surrounding_code: str | None = None,
    ) -> SlopClassificationResult:
        """Classifies a single comment or docstring block as human, ai_slop, or mixed."""
        cleaned = text.strip()
        if not cleaned:
            return SlopClassificationResult(
                label="human",
                confidence=1.0,
                slop_score=0.0,
                explanation="Empty text is considered clean.",
            )

        raw_score, markers, features = self._extract_heuristic_features(cleaned)

        # Check echo redundancy if code context is provided
        if surrounding_code:
            echo_ratio = self._calculate_echo_redundancy(cleaned, surrounding_code)
            features["echo_redundancy"] = echo_ratio
            if echo_ratio >= 0.75:
                raw_score += 25.0
                markers.append("echo_redundancy")

        # Use scikit-learn vectorizer if available to adjust confidence/score
        if self._sklearn_available and self._vectorizer:
            try:
                vec = self._vectorizer.transform([cleaned.lower()])
                tfidf_sum = float(vec.sum())
                features["tfidf_slop_density"] = tfidf_sum
                raw_score += tfidf_sum * 15.0
            except Exception as err:
                logger.debug(f"Tfidf transform error: {err}")

        # Normalize score to 0..100 scale
        normalized_score = min(100.0, round(raw_score, 1))

        if normalized_score >= 55.0:
            label = "ai_slop"
            confidence = min(0.99, max(0.65, normalized_score / 100.0))
            explanation = f"Detected {len(markers)} AI slop indicators: {', '.join(markers[:4])}"
        elif normalized_score >= 25.0:
            label = "mixed"
            confidence = 0.55 + (normalized_score / 200.0)
            explanation = f"Moderate AI slop indicators present: {', '.join(markers[:3])}"
        else:
            label = "human"
            confidence = 1.0 - (normalized_score / 100.0)
            explanation = "Authentic code commentary without prominent AI slop markers."

        return SlopClassificationResult(
            label=label,
            confidence=round(confidence, 3),
            slop_score=normalized_score,
            features=features,
            matched_markers=markers,
            explanation=explanation,
        )

    def analyze_source_content(
        self,
        content: str,
        filename: str = "",
    ) -> dict[str, Any]:
        """Analyzes all comments and docstrings in a file and returns aggregated slop statistics."""
        lines = content.splitlines()
        comment_findings: list[dict[str, Any]] = []
        slop_count = 0
        mixed_count = 0
        total_comments = 0

        for idx, line in enumerate(lines, start=1):
            stripped = line.strip()
            if not stripped.startswith("#"):
                continue

            total_comments += 1
            # Lookahead to next non-empty line for code context
            next_code = None
            for lookahead_idx in range(idx, min(idx + 3, len(lines))):
                candidate = lines[lookahead_idx].strip()
                if candidate and not candidate.startswith("#"):
                    next_code = candidate
                    break

            res = self.classify_text(stripped, surrounding_code=next_code)
            if res.label in ("ai_slop", "mixed"):
                if res.label == "ai_slop":
                    slop_count += 1
                else:
                    mixed_count += 1

                comment_findings.append({
                    "line": idx,
                    "comment": stripped[:120],
                    "label": res.label,
                    "confidence": res.confidence,
                    "slop_score": res.slop_score,
                    "markers": res.matched_markers,
                })

        slop_ratio = round((slop_count + 0.5 * mixed_count) / max(1, total_comments), 3)

        return {
            "filename": filename,
            "total_comments": total_comments,
            "slop_comments_count": slop_count,
            "mixed_comments_count": mixed_count,
            "slop_ratio": slop_ratio,
            "is_heavily_slop": slop_ratio >= 0.40 and slop_count >= 2,
            "findings": comment_findings[:50],
        }
