"""BDD and Gherkin Scenario Documentation Generator for WARDEN (Section D4).

Extracts behavioral specifications (Given-When-Then) from existing Python test suites
using Python AST analysis and optional LLM semantic enrichment.
Generates:
1. Standard Gherkin '.feature' files (compatible with Behave / Cucumber).
2. Comprehensive Markdown BDD documentation catalog ('TEST_SCENARIOS.md').
3. Structured JSON test catalog for dashboards and automated compliance audits.
"""

from __future__ import annotations

import ast
import logging
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

COMPARISON_OPERATORS: dict[type[ast.cmpop], str] = {
    ast.Eq: "should equal",
    ast.NotEq: "should not equal",
    ast.Lt: "should be less than",
    ast.LtE: "should be at most",
    ast.Gt: "should be greater than",
    ast.GtE: "should be at least",
    ast.Is: "should be",
    ast.IsNot: "should not be",
    ast.In: "should be included in",
    ast.NotIn: "should not be included in",
}


@dataclass
class BDDStep:
    """Represents a single Given, When, Then, or And step in a Gherkin scenario."""

    step_type: str  # "Given" | "When" | "Then" | "And"
    text: str
    code_snippet: str | None = None

    def to_gherkin(self) -> str:
        return f"    {self.step_type} {self.text}"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class BDDScenario:
    """Represents a BDD scenario extracted from a Python test function."""

    name: str
    description: str
    source_file: str
    test_function: str
    line_number: int
    tags: list[str] = field(default_factory=list)
    steps: list[BDDStep] = field(default_factory=list)

    def to_gherkin(self) -> str:
        lines: list[str] = []
        if self.tags:
            lines.append("  " + " ".join(f"@{t.lstrip('@')}" for t in self.tags))
        lines.append(f"  Scenario: {self.name}")
        if self.description:
            lines.append(f"    # {self.description.strip()}")
        for s in self.steps:
            lines.append(s.to_gherkin())
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "description": self.description,
            "source_file": self.source_file,
            "test_function": self.test_function,
            "line_number": self.line_number,
            "tags": self.tags,
            "steps": [s.to_dict() for s in self.steps],
        }


@dataclass
class BDDFeature:
    """Represents a Gherkin feature file extracted from a test file or test class."""

    feature_name: str
    description: str
    source_file: str
    scenarios: list[BDDScenario] = field(default_factory=list)
    tags: list[str] = field(default_factory=lambda: ["generated", "warden"])

    def to_gherkin(self) -> str:
        tag_line = " ".join(f"@{t.lstrip('@')}" for t in self.tags)
        lines = [
            f"# Auto-generated by WARDEN BDD Engine (Section D4)",
            f"# Source: {self.source_file}",
            f"{tag_line}",
            f"Feature: {self.feature_name}",
        ]
        if self.description:
            for desc_line in self.description.strip().splitlines():
                lines.append(f"  {desc_line.strip()}")
        else:
            lines.append("  As a Quality Engineer")
            lines.append("  I want to verify software behavior and invariants")
            lines.append("  So that high reliability and safety standards are maintained")
        lines.append("")
        for sc in self.scenarios:
            lines.append(sc.to_gherkin())
            lines.append("")
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        return {
            "feature_name": self.feature_name,
            "description": self.description,
            "source_file": self.source_file,
            "tags": self.tags,
            "scenarios_count": len(self.scenarios),
            "scenarios": [s.to_dict() for s in self.scenarios],
        }


@dataclass
class BDDSuiteReport:
    """Aggregated documentation report for all analyzed test features and scenarios."""

    target_path: str
    total_features: int
    total_scenarios: int
    total_steps: int
    features: list[BDDFeature] = field(default_factory=list)
    summary: str = ""

    def to_markdown(self) -> str:
        lines: list[str] = [
            "# 🥒 WARDEN BDD Senaryo & Test Dokümantasyon Kataloğu",
            "",
            f"> **Hedef Dizin:** `{self.target_path}`  ",
            f"> **Toplam Özellik (Features):** {self.total_features} | **Toplam Senaryo:** {self.total_scenarios} | **Toplam Adım (Steps):** {self.total_steps}",
            "",
            "---",
            "",
            "## 📑 Özellik İndeksi",
            "",
            "| # | Özellik (Feature) | Kaynak Test Dosyası | Senaryo Sayısı | Etiketler |",
            "|---|---|---|---|---|",
        ]

        for i, feat in enumerate(self.features, start=1):
            tags_str = ", ".join(f"`@{t}`" for t in feat.tags)
            lines.append(
                f"| {i} | **{feat.feature_name}** | `{Path(feat.source_file).name}` | {len(feat.scenarios)} | {tags_str} |"
            )

        lines.append("\n---\n")

        for feat in self.features:
            lines.append(f"## 📦 Özellik: {feat.feature_name}")
            lines.append(f"📁 **Kaynak:** `{feat.source_file}`  ")
            if feat.tags:
                lines.append(f"🏷️ **Etiketler:** {' '.join(f'`@{t}`' for t in feat.tags)}  ")
            lines.append(f"\n{feat.description}\n")

            for sc in feat.scenarios:
                lines.append(f"### 🎯 Senaryo: {sc.name}")
                if sc.description:
                    lines.append(f"*{sc.description.strip()}*\n")
                lines.append(f"- **Test Fonksiyonu:** `{sc.test_function}` (Satır {sc.line_number})")
                if sc.tags:
                    lines.append(f"- **Etiketler:** {' '.join(f'`@{t}`' for t in sc.tags)}")

                lines.append("\n```gherkin")
                lines.append(sc.to_gherkin())
                lines.append("```\n")

        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        return {
            "target_path": self.target_path,
            "total_features": self.total_features,
            "total_scenarios": self.total_scenarios,
            "total_steps": self.total_steps,
            "summary": self.summary,
            "features": [f.to_dict() for f in self.features],
        }


class ASTScenarioExtractor:
    """Extracts BDD features, scenarios, and steps from Python test ASTs."""

    COMMON_FIXTURES: dict[str, str] = {
        "client": "the HTTP API test client is initialized",
        "tmp_path": "a temporary directory fixture is prepared",
        "capsys": "stdout and stderr capture fixtures are active",
        "monkeypatch": "runtime environment monkeypatching is configured",
    }

    def __init__(self) -> None:
        pass

    def _clean_snake_name(self, name: str) -> str:
        """Converts snake_case test name to human-readable sentence."""
        clean = re.sub(r"^test_", "", name)
        words = clean.replace("_", " ").strip().capitalize()
        return words

    def _infer_tags(self, file_path: str, func_name: str) -> list[str]:
        """Infers Gherkin tags based on file path and function name."""
        tags: list[str] = ["unit"]
        path_lower = file_path.lower()
        func_lower = func_name.lower()

        if "api" in path_lower or "client" in func_lower or "endpoint" in func_lower:
            tags.append("api")
            tags.append("integration")
        if "security" in path_lower or "cve" in func_lower or "secret" in func_lower:
            tags.append("security")
        if "anomaly" in path_lower or "outlier" in func_lower or "mahalanobis" in func_lower:
            tags.append("anomaly")
        if "mutation" in path_lower or "mutant" in func_lower:
            tags.append("mutation")
        if "critical" in func_lower or "corrupted" in func_lower or "negative" in func_lower:
            tags.append("critical")
        if "cli" in path_lower or "command" in func_lower:
            tags.append("cli")

        return sorted(list(set(tags)))

    def _parse_assert_expression(self, node: ast.Assert) -> str:
        """Translates an AST Assert node into a human-readable Then statement."""
        test_expr = node.test

        # Case 1: ast.Compare (e.g. res.status_code == 200)
        if isinstance(test_expr, ast.Compare):
            left_str = ast.unparse(test_expr.left)
            ops_strs = []
            for op, comparator in zip(test_expr.ops, test_expr.comparators):
                op_phrase = COMPARISON_OPERATORS.get(type(op), "should satisfy comparison with")
                right_str = ast.unparse(comparator)
                ops_strs.append(f"{op_phrase} {right_str}")
            return f"'{left_str}' {' and '.join(ops_strs)}"

        # Case 2: ast.UnaryOp Not (e.g. not report.is_anomaly)
        if isinstance(test_expr, ast.UnaryOp) and isinstance(test_expr.op, ast.Not):
            operand_str = ast.unparse(test_expr.operand)
            return f"'{operand_str}' should be false"

        # Case 3: ast.Call (e.g. callable(res) or hasattr(obj, 'attr'))
        if isinstance(test_expr, ast.Call):
            call_str = ast.unparse(test_expr)
            return f"'{call_str}' should evaluate to true"

        # Default fallback
        expr_str = ast.unparse(test_expr)
        return f"'{expr_str}' should be satisfied"

    def _extract_steps_from_function(
        self,
        func_node: ast.FunctionDef | ast.AsyncFunctionDef,
    ) -> list[BDDStep]:
        """Extracts Given, When, Then steps from statements in a test function body."""
        raw_steps: list[tuple[str, str, str | None]] = []

        # 1. Given: Inspect test function arguments / fixtures
        arg_names = [arg.arg for arg in func_node.args.args if arg.arg != "self"]
        for arg in arg_names:
            desc = self.COMMON_FIXTURES.get(arg, f"test fixture '{arg}' is provided")
            raw_steps.append(("Given", desc, f"fixture: {arg}"))

        # 2. Inspect body statements
        for stmt in func_node.body:
            # Skip docstrings
            if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant) and isinstance(stmt.value.value, str):
                continue

            snippet = ast.unparse(stmt)

            # When: Check if statement is an API call or function execution
            if isinstance(stmt, ast.Assign):
                target_str = ast.unparse(stmt.targets[0])
                val_node = stmt.value

                if isinstance(val_node, ast.Call):
                    func_str = ast.unparse(val_node.func)
                    # Check if it looks like an action/when
                    if any(act in func_str for act in ["get", "post", "put", "delete", "evaluate", "forecast", "analyze", "scan", "run", "detect"]):
                        action_desc = f"'{func_str}' is invoked and result is stored in '{target_str}'"
                        raw_steps.append(("When", action_desc, snippet))
                        continue
                    else:
                        # Setup assignment -> Given
                        raw_steps.append(("Given", f"'{target_str}' is initialized with '{func_str}(...)'", snippet))
                        continue
                else:
                    # Variable setup -> Given
                    raw_steps.append(("Given", f"test data '{target_str}' is defined", snippet))
                    continue

            # When: Free function or method invocation
            if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Call):
                call_func = ast.unparse(stmt.value.func)
                raw_steps.append(("When", f"the action '{call_func}' is executed", snippet))
                continue

            # Then: Assertion statement
            if isinstance(stmt, ast.Assert):
                assert_text = self._parse_assert_expression(stmt)
                raw_steps.append(("Then", assert_text, snippet))
                continue

            # Then: pytest.raises with block
            if isinstance(stmt, ast.With):
                for item in stmt.items:
                    ctx = item.context_expr
                    if isinstance(ctx, ast.Call) and "raises" in ast.unparse(ctx.func):
                        exc_name = ast.unparse(ctx.args[0]) if ctx.args else "an expected"
                        match_arg = ""
                        for kw in ctx.keywords:
                            if kw.arg == "match":
                                match_arg = f" with message matching '{ast.unparse(kw.value)}'"
                        raw_steps.append(("Then", f"{exc_name} exception should be raised{match_arg}", snippet))

        # Default fallback steps if function body is minimal
        if not any(s[0] == "Given" for s in raw_steps):
            raw_steps.insert(0, ("Given", "the system test environment is prepared", None))
        if not any(s[0] == "When" for s in raw_steps):
            raw_steps.append(("When", f"the test function '{func_node.name}' executes", None))
        if not any(s[0] == "Then" for s in raw_steps):
            raw_steps.append(("Then", "the expected assertions must succeed without errors", None))

        # 3. Format consecutive same-type steps with "And"
        final_steps: list[BDDStep] = []
        last_primary_type: str | None = None

        for step_type, text, snip in raw_steps:
            if step_type == last_primary_type:
                final_steps.append(BDDStep(step_type="And", text=text, code_snippet=snip))
            else:
                final_steps.append(BDDStep(step_type=step_type, text=text, code_snippet=snip))
                last_primary_type = step_type

        return final_steps

    def extract_from_source(self, source_code: str, file_path: str = "test_module.py") -> list[BDDFeature]:
        """Parses Python source code and extracts BDD features and scenarios."""
        try:
            tree = ast.parse(source_code)
        except SyntaxError as err:
            logger.warning(f"Could not parse AST for {file_path}: {err}")
            return []

        features: list[BDDFeature] = []
        base_name = Path(file_path).stem
        module_doc = ast.get_docstring(tree) or f"Automated behavior specifications for {base_name}"

        # 1. Process classes (TestClasses)
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and (node.name.startswith("Test") or node.name.endswith("Test") or node.name.endswith("Tests")):
                class_doc = ast.get_docstring(node) or module_doc
                feat_name = re.sub(r"^Test", "", node.name)
                feat_name = re.sub(r"([A-Z])", r" \1", feat_name).strip()

                scenarios: list[BDDScenario] = []
                for sub_node in node.body:
                    if isinstance(sub_node, (ast.FunctionDef, ast.AsyncFunctionDef)) and sub_node.name.startswith("test_"):
                        sc_doc = ast.get_docstring(sub_node) or ""
                        sc_name = self._clean_snake_name(sub_node.name)
                        tags = self._infer_tags(file_path, sub_node.name)
                        steps = self._extract_steps_from_function(sub_node)

                        scenarios.append(
                            BDDScenario(
                                name=sc_name,
                                description=sc_doc,
                                source_file=file_path,
                                test_function=f"{node.name}.{sub_node.name}",
                                line_number=sub_node.lineno,
                                tags=tags,
                                steps=steps,
                            )
                        )

                if scenarios:
                    features.append(
                        BDDFeature(
                            feature_name=feat_name or base_name,
                            description=class_doc,
                            source_file=file_path,
                            scenarios=scenarios,
                            tags=self._infer_tags(file_path, node.name),
                        )
                    )

        # 2. Process top-level test functions (not in a class)
        top_scenarios: list[BDDScenario] = []
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test_"):
                sc_doc = ast.get_docstring(node) or ""
                sc_name = self._clean_snake_name(node.name)
                tags = self._infer_tags(file_path, node.name)
                steps = self._extract_steps_from_function(node)

                top_scenarios.append(
                    BDDScenario(
                        name=sc_name,
                        description=sc_doc,
                        source_file=file_path,
                        test_function=node.name,
                        line_number=node.lineno,
                        tags=tags,
                        steps=steps,
                    )
                )

        if top_scenarios:
            feat_name = base_name.replace("test_", "").replace("_", " ").title()
            features.append(
                BDDFeature(
                    feature_name=f"{feat_name} Suite",
                    description=module_doc,
                    source_file=file_path,
                    scenarios=top_scenarios,
                    tags=self._infer_tags(file_path, base_name),
                )
            )

        return features

    def extract_from_file(self, file_path: Path | str) -> list[BDDFeature]:
        """Reads a test file from disk and parses its AST."""
        p = Path(file_path).resolve()
        if not p.is_file():
            return []

        try:
            source = p.read_text(encoding="utf-8")
        except Exception as err:
            logger.warning(f"Failed to read file {p}: {err}")
            return []

        return self.extract_from_source(source, file_path=str(p))


class BDDScenarioGeneratorService:
    """Service for discovering test files, generating BDD features, and exporting documentation."""

    def __init__(self) -> None:
        self.extractor = ASTScenarioExtractor()

    def generate_from_path(
        self,
        target_path: Path | str = "tests",
        enrich_with_llm: bool = False,
        provider_name: str | None = None,
        max_files: int = 50,
    ) -> BDDSuiteReport:
        """Extracts BDD features and scenarios from a directory or single test file."""
        p = Path(target_path).resolve()
        features: list[BDDFeature] = []

        if p.is_file():
            features.extend(self.extractor.extract_from_file(p))
        elif p.is_dir():
            test_files = sorted(list(p.rglob("test_*.py")))[:max_files]
            for tf in test_files:
                # Ignore fixtures or venv
                if "fixtures" in tf.parts or ".venv" in tf.parts:
                    continue
                features.extend(self.extractor.extract_from_file(tf))

        total_scenarios = sum(len(f.scenarios) for f in features)
        total_steps = sum(sum(len(s.steps) for s in f.scenarios) for f in features)

        # Optional LLM enrichment
        if enrich_with_llm and features:
            self._enrich_features_with_llm(features, provider_name=provider_name)

        summary = (
            f"Toplam {len(features)} BDD Özelliği (Feature), {total_scenarios} Davranış Senaryosu "
            f"ve {total_steps} Given-When-Then adımı başarıyla çıkarıldı."
        )

        return BDDSuiteReport(
            target_path=str(p),
            total_features=len(features),
            total_scenarios=total_scenarios,
            total_steps=total_steps,
            features=features,
            summary=summary,
        )

    def _enrich_features_with_llm(
        self,
        features: list[BDDFeature],
        provider_name: str | None = None,
    ) -> None:
        """Enriches feature and scenario descriptions with business domain language using LLM."""
        try:
            from core.llm.factory import LLMProviderFactory

            provider = LLMProviderFactory.create(provider_name or "gemini")
            # Sample first few features to enrich
            for feat in features[:5]:
                scenario_names = [s.name for s in feat.scenarios[:5]]
                prompt = (
                    f"Aşağıdaki test özellik adı ve senaryoları için standart BDD formatında "
                    f"(As a <role>, I want <goal>, So that <benefit>) 3 satırlık bir Feature Açıklaması üret:\n"
                    f"Feature: {feat.feature_name}\n"
                    f"Senaryolar: {', '.join(scenario_names)}\n"
                    f"Sadece 3 satırlık BDD açıklamasını döndür:"
                )
                enriched_text = provider.generate_text(prompt)
                if enriched_text and "As a" in enriched_text:
                    feat.description = enriched_text.strip()
        except Exception as err:
            logger.debug(f"LLM enrichment skipped or failed gracefully: {err}")

    def export_feature_files(
        self,
        report: BDDSuiteReport,
        output_dir: Path | str,
    ) -> list[Path]:
        """Writes Behave/Cucumber compatible .feature files into the specified directory."""
        out_dir = Path(output_dir).resolve()
        out_dir.mkdir(parents=True, exist_ok=True)

        exported_paths: list[Path] = []
        for feat in report.features:
            safe_name = re.sub(r"[^\w\-]", "_", feat.feature_name.lower().strip())
            file_name = f"{safe_name}.feature"
            target_file = out_dir / file_name

            gherkin_content = feat.to_gherkin()
            target_file.write_text(gherkin_content, encoding="utf-8")
            exported_paths.append(target_file)

        return exported_paths

    def export_markdown_report(
        self,
        report: BDDSuiteReport,
        output_file: Path | str,
    ) -> Path:
        """Writes Markdown BDD documentation catalog to a file."""
        out_file = Path(output_file).resolve()
        out_file.parent.mkdir(parents=True, exist_ok=True)

        md_content = report.to_markdown()
        out_file.write_text(md_content, encoding="utf-8")
        return out_file
