"""AI-Generated Commit Message Detector for WARDEN.

Analyzes Git commit messages to detect synthetic, LLM-generated commits
produced by tools like GitHub Copilot, Cursor, or ChatGPT:
- Formal, textbook phrasing ("adhere to SOLID principles", "enhance modularity")
- Characteristic sentence templates ("Action + Object + 'in order to ensure' + Justification")
- Diff-echoing bulleted changelogs with conversational tone
- Robotic boilerplate ("This commit introduces...", "Refactored to align with best practices")
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)

# Heuristic patterns that frequently appear in LLM-generated commit messages
AI_COMMIT_PATTERNS: list[tuple[re.Pattern[str], str, float]] = [
    (
        re.compile(r"\b(adhere(s|ing)?\s+to\s+(clean\s+code|solid(\s+principles)?|best\s+practices))\b", re.IGNORECASE),
        "formal_buzzwords",
        3.5,
    ),
    (
        re.compile(r"\b(enhance(s|d)?|improves?)\s+(modularity|maintainability|scalability|readability|robustness)\b", re.IGNORECASE),
        "formal_enhancement_cliche",
        3.0,
    ),
    (
        re.compile(r"\b(this\s+commit\s+(introduces|adds|refactors|implements|modifies|updates|ensures))\b", re.IGNORECASE),
        "conversational_self_reference",
        4.0,
    ),
    (
        re.compile(r"\b(in\s+order\s+to\s+(ensure|provide|guarantee|enhance|prevent))\b", re.IGNORECASE),
        "verbose_justification",
        2.5,
    ),
    (
        re.compile(r"\b(comprehensive\s+(error\s+handling|logging|test\s+coverage|suite|implementation))\b", re.IGNORECASE),
        "comprehensive_cliche",
        2.5,
    ),
    (
        re.compile(r"\b(seamless(ly)?(\s+\w+)?)\b", re.IGNORECASE),
        "ai_buzzword_seamless",
        2.5,
    ),
    (
        re.compile(r"\b(robust\s+and\s+(scalable|maintainable|efficient))\b", re.IGNORECASE),
        "ai_pair_buzzwords",
        3.5,
    ),
]

# Patterns for bulleted diff-echoing lists typical of Copilot/Cursor auto-generated messages
BULLET_ECHO_PATTERN = re.compile(
    r"(?m)^\s*[-*•]\s+(Added|Updated|Refactored|Fixed|Ensured|Implemented|Removed)\s+.*$",
)


@dataclass
class CommitAIClassification:
    """Classification of an individual commit message."""

    message: str
    is_ai_generated: bool
    ai_confidence: float  # 0.0 to 1.0
    ai_score: float  # 0.0 to 100.0
    indicators: list[str] = field(default_factory=list)
    explanation: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "message": self.message[:100],
            "is_ai_generated": self.is_ai_generated,
            "ai_confidence": round(self.ai_confidence, 3),
            "ai_score": round(self.ai_score, 1),
            "indicators": self.indicators,
            "explanation": self.explanation,
        }


class CommitAIDetector:
    """Detects whether Git commit messages were generated by AI assistants."""

    def classify_message(self, message: str) -> CommitAIClassification:
        """Classifies a commit message as AI-generated or human-written."""
        cleaned = message.strip()
        if not cleaned:
            return CommitAIClassification(
                message="",
                is_ai_generated=False,
                ai_confidence=0.0,
                ai_score=0.0,
                explanation="Empty commit message.",
            )

        indicators: list[str] = []
        raw_score = 0.0

        # 1. Pattern checks
        for pat, tag, weight in AI_COMMIT_PATTERNS:
            if pat.search(cleaned):
                indicators.append(tag)
                raw_score += weight * 15.0

        # 2. Bullet point diff-mirroring check
        bullets = BULLET_ECHO_PATTERN.findall(cleaned)
        if len(bullets) >= 4:
            indicators.append(f"multi_bullet_diff_echo({len(bullets)})")
            raw_score += 50.0
        elif len(bullets) >= 3:
            indicators.append(f"multi_bullet_diff_echo({len(bullets)})")
            raw_score += 45.0
        elif len(bullets) >= 2:
            indicators.append("bullet_echo")
            raw_score += 25.0

        # 3. Message length & structure analysis
        lines = [line.strip() for line in cleaned.splitlines() if line.strip()]
        words = cleaned.split()

        # Overly verbose single-line subject (> 90 chars with formal verbs)
        if len(lines) == 1 and len(cleaned) > 85 and any(tag in indicators for tag in ("formal_buzzwords", "formal_enhancement_cliche", "verbose_justification")):
            indicators.append("verbose_formal_subject")
            raw_score += 20.0

        # Short human-like commits exemption (e.g. "fix typo", "bump deps", "wip")
        if len(words) <= 5 and not indicators:
            raw_score = 0.0

        normalized_score = min(100.0, round(raw_score, 1))
        is_ai = normalized_score >= 45.0

        if is_ai:
            confidence = min(0.99, max(0.60, normalized_score / 100.0))
            explanation = f"Detected AI commit characteristics: {', '.join(indicators)}"
        elif normalized_score >= 20.0:
            confidence = 0.50
            explanation = "Borderline commit: exhibits mild formal or structural markers."
        else:
            confidence = 1.0 - (normalized_score / 100.0)
            explanation = "Commit message aligns with natural human developer conventions."

        return CommitAIClassification(
            message=cleaned,
            is_ai_generated=is_ai,
            ai_confidence=round(confidence, 3),
            ai_score=normalized_score,
            indicators=indicators,
            explanation=explanation,
        )

    def analyze_commit_batch(self, messages: list[str]) -> dict[str, Any]:
        """Analyzes a list of commit messages and computes aggregate AI statistics."""
        if not messages:
            return {
                "total_analyzed": 0,
                "ai_commits_count": 0,
                "ai_commits_ratio": 0.0,
                "findings": [],
            }

        classifications = [self.classify_message(msg) for msg in messages]
        ai_commits = [c for c in classifications if c.is_ai_generated]

        ratio = round(len(ai_commits) / len(messages), 4)

        return {
            "total_analyzed": len(messages),
            "ai_commits_count": len(ai_commits),
            "ai_commits_ratio": ratio,
            "findings": [c.to_dict() for c in ai_commits[:30]],
        }
