"""Comprehensive tests for scan_exclusions.py edge cases."""
from pathlib import Path
from unittest.mock import patch

from core.services.shared.scan_exclusions import (
    get_generated_files_from_gitattributes,
    is_duplication_excluded,
    is_generated_file,
    is_lockfile_or_vendor,
)


def test_is_duplication_excluded(tmp_path: Path):
    # Generated file exclusion
    gen_file = tmp_path / "schema_pb2.py"
    gen_file.write_text("# Generated by the protocol buffer compiler.  DO NOT EDIT!\n")
    assert is_duplication_excluded(gen_file, repo_path=tmp_path) is True

    # Migration file exclusion
    migration_file = tmp_path / "migrations" / "0001_initial.py"
    migration_file.parent.mkdir(parents=True, exist_ok=True)
    migration_file.write_text("# migration code")
    assert is_duplication_excluded(migration_file, repo_path=tmp_path) is True

    # models.py exclusion
    models_file = tmp_path / "models.py"
    models_file.write_text("class User:\n    pass\n")
    assert is_duplication_excluded(models_file, repo_path=tmp_path) is True

    # Normal python code
    normal_file = tmp_path / "services" / "payment.py"
    normal_file.parent.mkdir(parents=True, exist_ok=True)
    normal_file.write_text("class PaymentProcessor:\n    pass\n")
    assert is_duplication_excluded(normal_file, repo_path=tmp_path) is False


def test_is_generated_file_edge_cases(tmp_path: Path):
    # Test file reading marker
    f = tmp_path / "custom_gen.txt"
    f.write_text("/* Code generated by MockTool. DO NOT EDIT. */\nSome other code\n")
    is_gen, reason = is_generated_file(f, repo_path=tmp_path)
    assert is_gen is True
    assert "marker" in (reason or "")

    # Test OSError during file read
    with patch("builtins.open", side_effect=OSError("Read error")):
        is_gen_err, _ = is_generated_file(f, repo_path=tmp_path)
        assert is_gen_err is False

    # Test relative_to ValueError (different root)
    unrelated_path = Path("/different/root/path/file.py")
    is_gen_ext, _ = is_generated_file(unrelated_path, repo_path=tmp_path)
    assert is_gen_ext is False


def test_gitattributes_parsing(tmp_path: Path):
    # Case 1: .gitattributes doesn't exist
    assert get_generated_files_from_gitattributes(tmp_path) == set()

    # Case 2: .gitattributes exists with comments and valid entries
    gitattr = tmp_path / ".gitattributes"
    gitattr.write_text(
        "# This is a comment\n"
        "\n"
        "*.min.js linguist-generated=true\n"
        "bundle.js linguist-generated\n"
        "regular.py text\n"
    )
    res = get_generated_files_from_gitattributes(tmp_path)
    assert "*.min.js" in res

    # Case 3: OSError on reading
    with patch.object(Path, "read_text", side_effect=OSError("Read error")):
        assert get_generated_files_from_gitattributes(tmp_path) == set()


def test_is_lockfile_or_vendor_edge_cases(tmp_path: Path):
    # Relative path error fallback
    unrelated_lock = Path("/different/root/poetry.lock")
    assert is_lockfile_or_vendor(unrelated_lock, repo_path=tmp_path) is True

    # Standard exclusion check (node_modules)
    node_file = tmp_path / "node_modules" / "lib.js"
    assert is_lockfile_or_vendor(node_file, repo_path=tmp_path) is True
