"""Centralized scan exclusion lists and helpers for Layer 1 scanners."""

from pathlib import Path

STANDARD_EXCLUSIONS: list[str] = [
    ".git",
    ".venv",
    "venv",
    "env",
    ".env",
    "node_modules",
    "build",
    "dist",
    ".tox",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".idea",
    ".vscode",
]


import re

GENERATED_FILE_PATTERNS: list[str] = [
    r".*/migrations/.*\.py$",
    r"^migrations/.*\.py$",
    r".*_pb2\.py$",
    r".*/generated/.*",
    r"^generated/.*",
    r".*\.g\.py$",
]

GENERATED_MARKERS: list[str] = [
    "@generated",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "generated by",
]

DUPLICATION_ADDITIONAL_EXCLUSIONS: list[str] = [
    r".*/models\.py$",
    r"^models\.py$",
    r".*__init__\.py$",
    r"^__init__\.py$",
]


def get_scan_exclusions(repo_path: Path | None = None, extra: list[str] | None = None) -> list[str]:
    """Returns the unified list of directory and file exclusions.

    All Layer 1 scanners (ruff, radon, jscpd, ast analyzers) should use this single source of truth.
    """
    exclusions = list(STANDARD_EXCLUSIONS)
    if extra:
        exclusions.extend(extra)
    return exclusions


def get_scan_exclusion_pattern(
    repo_path: Path | None = None,
    extra: list[str] | None = None,
    include_generated: bool = True,
) -> str:
    """Returns a regex pattern of exclusions suitable for scanner arguments."""
    exclusions = get_scan_exclusions(repo_path, extra=extra)
    escaped = [re.escape(item) for item in exclusions]
    if include_generated:
        escaped.extend(GENERATED_FILE_PATTERNS)
    return f"({'|'.join(escaped)})"


def get_duplication_ignore_pattern(
    repo_path: Path | None = None,
    extra: list[str] | None = None,
) -> str:
    """Returns a comma-separated glob list suitable for jscpd's --ignore argument."""
    dirs = get_scan_exclusions(repo_path, extra=extra)
    globs = [f"**/{d}/**" for d in dirs]
    globs.extend([
        "**/migrations/**",
        "**/*_pb2.py",
        "**/*.g.py",
        "**/generated/**",
        "**/models.py",
        "**/__init__.py",
    ])
    return ",".join(globs)


def is_duplication_excluded(file_path: Path | str, repo_path: Path | None = None) -> bool:
    """Checks whether a file should be excluded from duplication detection."""
    is_gen, _ = is_generated_file(file_path, repo_path)
    if is_gen:
        return True

    path_obj = Path(file_path)
    if repo_path and path_obj.is_absolute():
        try:
            rel_str = str(path_obj.relative_to(repo_path))
        except ValueError:
            rel_str = str(path_obj)
    else:
        rel_str = str(path_obj)

    rel_str = rel_str.replace("\\", "/")
    for pattern in DUPLICATION_ADDITIONAL_EXCLUSIONS:
        if re.search(pattern, rel_str):
            return True
    return False


def is_generated_file(file_path: Path | str, repo_path: Path | None = None) -> tuple[bool, str | None]:
    """Checks whether a file is generated either by filepath pattern or header markers.

    Returns (True, reason) if generated, or (False, None) otherwise.
    """
    path_obj = Path(file_path)
    if repo_path and path_obj.is_absolute():
        try:
            rel_str = str(path_obj.relative_to(repo_path))
        except ValueError:
            rel_str = str(path_obj)
    else:
        rel_str = str(path_obj)

    # Normalize Windows backslashes
    rel_str = rel_str.replace("\\", "/")

    for pattern in GENERATED_FILE_PATTERNS:
        if re.search(pattern, rel_str):
            return True, f"pattern:{pattern}"

    if path_obj.is_file():
        full_path = path_obj
    elif repo_path and (repo_path / path_obj).is_file():
        full_path = repo_path / path_obj
    else:
        full_path = path_obj

    if full_path.is_file():
        try:
            with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                for _ in range(5):
                    line = f.readline()
                    if not line:
                        break
                    lower_line = line.lower()
                    for marker in GENERATED_MARKERS:
                        if marker in lower_line:
                            return True, f"marker:{marker}"
        except OSError:
            pass

    return False, None

